FROM centos:7

RUN yum install yum-utils wget httpd -y

RUN yum install -y http://rpms.remirepo.net/enterprise/remi-release-7.rpm \
 && yum-config-manager --enable remi-php73 \
 && yum install -y epel-release \
 && yum install -y php php-zip php-gd php-intl php-mbstring php-soap php-xmlrpc php-pgsql \
      php-opcache php-mysqli \
 && yum clean all

EXPOSE 80

ENTRYPOINT ["/usr/sbin/httpd", "-D", "FOREGROUND"]
