apiVersion: batch/v1
kind: Job
metadata:
  name: moodle-initial-job
spec:
  template:
    metadata:
      labels:
        job: moodle-initial-job
    spec:
      nodeSelector:
        node: "web"
      containers:
      - name: main
        image: busybox
        volumeMounts:
        - name: moodle-pvc
          mountPath: /moodle
        command: [ "sh", "-c", "wget https://download.moodle.org/download.php/direct/stable38/moodle-3.8.tgz -O - | tar -xz -f - -C /moodle/ ; mv -f /moodle/moodle /moodle/html ; mkdir /moodle/moodledata " ]
#        command: ["sleep", "9999999"]
      restartPolicy: OnFailure
      volumes:
      - name: moodle-pvc 
        persistentVolumeClaim: 
          claimName: moodle-pvc 
