apiVersion: v1
kind: ReplicationController
metadata:
  name: moodle-rc
spec:
  replicas: 2
  selector:
    app: moodle-pod
  template:
    metadata:
      labels:
        app: moodle-pod
    spec:
      nodeSelector:
        node: "web"
      containers:
      - name: moodle-con
        image: rmamchur/apache:0
        readinessProbe:
          periodSeconds: 10
          httpGet:
            path: /install/welcome.html 
            port: 80
        ports:
        - name: http
          containerPort: 80
        volumeMounts:
        - name: moodle-pvc 
          mountPath: /var/www
        resources:
          requests:
            cpu: 100m
#        command: ["sleep", "9999999"]
      volumes:
      - name: moodle-pvc 
        persistentVolumeClaim:
          claimName: moodle-pvc 

