apiVersion: v1
kind: ReplicationController
metadata:
  name: wp-web
spec:
  replicas: 2
  selector:
    app: wp-web
  template:
    metadata:
      labels:
        app: wp-web
    spec:
      nodeSelector:
        app: "web"
      containers:
      - name: wp-web
        image: rmamchur/apache:0
        readinessProbe:
          periodSeconds: 10
          httpGet:
            path: /readme.html
            port: 80
        ports:
        - name: http
          containerPort: 80
        volumeMounts:
        - name: wp-pvc 
          mountPath: /var/www/html
        - name: wp-conf
          mountPath: /var/www/html/wp-config.php
          subPath: wp-config.php
        resources:
          requests:
            cpu: 100m
      volumes:
      - name: wp-pvc 
        persistentVolumeClaim:
          claimName: wp-pvc 
      - name: wp-conf
        secret:
          secretName: wp-conf

