apiVersion: batch/v1
kind: Job
metadata:
  name: moodle-initial-job
spec:
  template:
    metadata:
      labels:
        job: moodle-initial-job
    spec:
      nodeSelector:
        node: "web"
      initContainers:
      - name: init-db
        image: rmamchur/i_my:2
        command:
        - sh
        - -c
        - 'until mysqladmin --host=mysql --user=moodle --password="Passw0rd(" ping; do echo waiting for mydb; sleep 2; done; echo "MySql is run."'
      containers:
      - name: main
        image: rmamchur/apache:2
        volumeMounts:
        - name: moodle-pvc
          mountPath: /var/www
        - name: git-rm
          mountPath: /git_rm
        command: [ "sh", "-c", "chmod 777 /git_rm/moodle_init.sh ; /git_rm/moodle_init.sh " ]
      restartPolicy: OnFailure
      volumes:
      - name: moodle-pvc 
        persistentVolumeClaim: 
          claimName: moodle-pvc 
      - name:  git-rm
        gitRepo:
          repository: https://github.com/r-mamchur/GKE_Exercise_1.git
          revision: master
          directory: .
