apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: moodle-deployment-hpa
spec:
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - resource:
      name: cpu
      targetAverageUtilization: 30
    type: Resource
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: moodle-deployment
